leftnav:
- identifier: 8a91fcd1-5a83-8151-4ddd-974660d7beb9
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 81b3f84c-39ed-3777-b858-4e0393fb60d0
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 0df961ea-2619-83ce-3f52-134876e2b011
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: d23ae896-1a53-047f-6102-40b0f0bf7128
  name: Assignments
  url: /pages/assignments
  weight: 40
- identifier: 9d5212d1-ea7f-9d55-b2b7-834d3f6ac7fc
  name: Exams
  url: /pages/exams
  weight: 50
- identifier: ceaa7cb0-f7c9-dcc8-a9cf-1ddba72b9f05
  name: Projects
  url: /pages/projects
  weight: 60
- identifier: f3f45995-cb15-2582-293f-ac2610a4fead
  name: Listening
  url: /pages/listening
  weight: 70
